### ISSUE TITLE
Error in Kodi Nexus v20 on AppleTv - Highlight color not rendered

### ISSUE THREAD

**Issue by eengert** [jurialmunkey/script.texturemaker#1]
Just FYI, I tested AH2 on Kodi Nexus v20 on AppleTv 4K.  Everything seems to work except TextureMaker errors whenever it is invoked. When I try to set the colors for AH2, the color picker is blank and I get a notification that a TextureMaker error occurred. Even manually setting the color hex code doesn’t work. The highlight/button background is not rendered. This makes it difficult to tell what is currently in focus.

**Comment by jurialmunkey** [comment]
debug log?

**Comment by eengert** [comment]
Log file:  [https://paste.kodi.tv/oyebubaten](https://paste.kodi.tv/oyebubaten)

**Comment by eengert** [comment]
FYI, this also happens on a clean install of Kodi v20 Alpha 1 on MacOS. 

Log file:  [https://paste.kodi.tv/kupojiligo](https://paste.kodi.tv/kupojiligo)

**Comment by jurialmunkey** [comment]
It's a PIL module issue. Not much I can do about it. PIL module support would need to be fixed on that platform for Nexus.

**Comment by jurialmunkey** [comment]
There was a similar issue in one of the Matrix alpha's
https://forum.kodi.tv/showthread.php?tid=356325

**Comment by jurialmunkey** [comment]
Key point in log - you're missing an important python module
`ModuleNotFoundError: No module named 'pkg_resources'`

Possible solutions here:
https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

**Comment by eengert** [comment]
I'm not exactly sure what to do with this information.  Is there a way that I can install a python module on my Apple TV?

**Comment by jurialmunkey** [comment]
Don't have an apple TV so I have no idea. Normally python modules are packaged with kodi to ensure consistency but some OS/platforms need to use the system ones instead for various reasons.

Either way it's a Nexus bug with Kodi that should be reported and needs to be fixed. Nothing can be done from my side of things as that is a standard python module so if it doesn't work then a lot of things will break, not just my script.

**Comment by eengert** [comment]
FYI, I opened an issue in github for Kodi:  [https://github.com/xbmc/xbmc/issues/21524](https://github.com/xbmc/xbmc/issues/21524)

**Comment by eengert** [comment]
The missing python module is indeed the cause of this issue.  One of the Kodi devs has already fixed the issue on MacOS, and should have a fix for TvOS in the next day or two:  [https://github.com/xbmc/xbmc/issues/21524](https://github.com/xbmc/xbmc/issues/21524) .  I'm closing this issue here since it's not caused by TextureMaker.

**Comment by jurialmunkey** [comment]
Excellent news! Nice to hear it was fixed so quickly.
